name: flutter_gl_web_flutterflow
description: Web platform implementation of flutter_gl_flutterflow. Fixed platformViewRegistry deprecation for Flutter 3.32.4+. OpenGL API through dart:ffi with Texture Widget.
homepage: https://github.com/evt-app-eng/flutter_gl_flutterflow
repository: https://github.com/evt-app-eng/flutter_gl_flutterflow
version: 0.0.6

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterGlPlugin
        fileName: flutter_gl_web.dart

dependencies:  
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_gl_platform_interface_flutterflow: ^0.0.5
 
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
